import pandas as pd
import numpy as np
import os

class FeatureExtractor:
    def __init__(self):
        # Load the latest datasets generated by the pipeline
        # Use paths relative to this file to handle different execution directories
        _dir = os.path.dirname(os.path.abspath(__file__))
        self.match_features_path = os.path.join(_dir, "feature_dataset_v3.csv")
        self.score_features_path = os.path.join(_dir, "score_prediction_training_v3.csv")
        self.playing11_features_path = os.path.join(_dir, "playing11_dataset.csv")

        self.df_match = None
        self.df_score = None
        self.df_playing11 = None
        self.load_errors = []
        
        # Encodings from training script
        self.team_reverse = {}
        self.opponent_reverse = {}
        self.venue_reverse = {}
        self.team_map = {}
        self.role_map = {}
        
        self.load_data()

    def load_data(self):
        """Loads or reloads the datasets."""
        try:
            if os.path.exists(self.match_features_path):
                self.df_match = pd.read_csv(self.match_features_path)
            
            if os.path.exists(self.score_features_path):
                self.df_score = pd.read_csv(self.score_features_path)
                
        except Exception as e:
            self.load_errors.append(f"Error loading CSVs: {e}")

        try:
            if os.path.exists(self.playing11_features_path):
                self.df_playing11 = pd.read_csv(self.playing11_features_path)
                self.df_playing11.fillna(0, inplace=True)
                
                # Precompute category codes like the training script
                team_cats = self.df_playing11['team'].astype('category').cat.categories
                opp_cats = self.df_playing11['opponent'].astype('category').cat.categories
                ven_cats = self.df_playing11['venue'].astype('category').cat.categories
                role_cats = self.df_playing11['player_role'].astype('category').cat.categories
                
                self.team_map = dict(enumerate(team_cats))
                self.role_map = dict(enumerate(role_cats))
                
                self.team_reverse = {v: k for k, v in self.team_map.items()}
                self.opponent_reverse = {v: k for k, v in dict(enumerate(opp_cats)).items()}
                self.venue_reverse = {v: k for k, v in dict(enumerate(ven_cats)).items()}
                
                # Apply encoding early so lookup is fast
                self.df_playing11['team'] = self.df_playing11['team'].astype('category').cat.codes
                self.df_playing11['opponent'] = self.df_playing11['opponent'].astype('category').cat.codes
                self.df_playing11['venue'] = self.df_playing11['venue'].astype('category').cat.codes
                self.df_playing11['player_role'] = self.df_playing11['player_role'].astype('category').cat.codes
                self.df_playing11['designation'] = self.df_playing11['designation'].astype('category').cat.codes
        except Exception as e:
            print(f"Error loading playing 11 dataset: {e}")

    def get_match_features(self, team1, team2, venue):
        """Extracts average historical features for Match Winner prediction."""
        if self.df_match is None or self.df_match.empty:
            return self._get_fallback_match_features(team1, team2, venue)
            
        # Get team overall win rates (average across all their matches)
        t1_overall_wr = self.df_match[(self.df_match['team1'] == team1) | (self.df_match['team2'] == team1)]['team1_overall_win_rate'].mean()
        t2_overall_wr = self.df_match[(self.df_match['team1'] == team2) | (self.df_match['team2'] == team2)]['team2_overall_win_rate'].mean()
        
        # Get venue specific averages
        v_data = self.df_match[self.df_match['venue'] == venue]
        avg_score_venue = v_data['avg_score_venue'].mean() if not v_data.empty else 160.0
        toss_venue_wr = v_data['toss_venue_win_rate'].mean() if not v_data.empty else 0.5
        
        # H2H and Form (approximated from latest available data for these teams)
        t1_recent = self.df_match[(self.df_match['team1'] == team1) | (self.df_match['team2'] == team1)]['recent_form_t1'].iloc[-1] if not self.df_match[(self.df_match['team1'] == team1) | (self.df_match['team2'] == team1)].empty else 0.5
        t2_recent = self.df_match[(self.df_match['team1'] == team2) | (self.df_match['team2'] == team2)]['recent_form_t2'].iloc[-1] if not self.df_match[(self.df_match['team1'] == team2) | (self.df_match['team2'] == team2)].empty else 0.5
        
        # H2H between these two specific teams 
        h2h_data = self.df_match[((self.df_match['team1'] == team1) & (self.df_match['team2'] == team2)) | 
                                 ((self.df_match['team1'] == team2) & (self.df_match['team2'] == team1))]
        h2h_wr = h2h_data['h2h_win_rate'].mean() if not h2h_data.empty else 0.5
        
        # Venue specific win rates for teams
        v_wr_t1 = v_data[(v_data['team1'] == team1) | (v_data['team2'] == team1)]['venue_win_rate_t1'].mean() if not v_data[(v_data['team1'] == team1) | (v_data['team2'] == team1)].empty else 0.5
        v_wr_t2 = v_data[(v_data['team1'] == team2) | (v_data['team2'] == team2)]['venue_win_rate_t2'].mean() if not v_data[(v_data['team1'] == team2) | (v_data['team2'] == team2)].empty else 0.5

        # Player stats
        t1_bat = self.df_match[(self.df_match['team1'] == team1) | (self.df_match['team2'] == team1)]['t1_top_batsmen_avg'].mean()
        t2_bat = self.df_match[(self.df_match['team1'] == team2) | (self.df_match['team2'] == team2)]['t2_top_batsmen_avg'].mean()
        t1_bowl = self.df_match[(self.df_match['team1'] == team1) | (self.df_match['team2'] == team1)]['t1_top_bowler_econ'].mean()
        t2_bowl = self.df_match[(self.df_match['team1'] == team2) | (self.df_match['team2'] == team2)]['t2_top_bowler_econ'].mean()

        def safe_val(val, default): return default if pd.isna(val) else val
        
        # Cleaned values
        c_t1_bat = safe_val(t1_bat, 35.0)
        c_t2_bat = safe_val(t2_bat, 30.0)
        c_t1_bowl = safe_val(t1_bowl, 7.5)
        c_t2_bowl = safe_val(t2_bowl, 8.0)
        c_t1_recent = safe_val(t1_recent, 0.5)
        c_t2_recent = safe_val(t2_recent, 0.5)
        c_t1_overall = safe_val(t1_overall_wr, 0.5)
        c_t2_overall = safe_val(t2_overall_wr, 0.5)
        c_v_wr_t1 = safe_val(v_wr_t1, 0.5)
        c_v_wr_t2 = safe_val(v_wr_t2, 0.5)

        return {
            'team1': team1,
            'team2': team2,
            'venue': venue,
            'first_innings_team': team1, 
            'h2h_win_rate': safe_val(h2h_wr, 0.5),
            'recent_form_t1': c_t1_recent,
            'recent_form_t2': c_t2_recent,
            'team1_overall_win_rate': c_t1_overall,
            'team2_overall_win_rate': c_t2_overall,
            'avg_score_venue': safe_val(avg_score_venue, 160.0),
            'toss_venue_win_rate': safe_val(toss_venue_wr, 0.5),
            'venue_win_rate_t1': c_v_wr_t1,
            'venue_win_rate_t2': c_v_wr_t2,
            't1_top_batsmen_avg': c_t1_bat,
            't2_top_batsmen_avg': c_t2_bat,
            't1_top_bowler_econ': c_t1_bowl,
            't2_top_bowler_econ': c_t2_bowl,
            
            # Exact features from user's model script
            'batting_diff': c_t1_bat - c_t2_bat,
            'bowling_diff': c_t2_bowl - c_t1_bowl,
            'recent_form_diff': c_t1_recent - c_t2_recent,
            'overall_winrate_diff': c_t1_overall - c_t2_overall,
            'venue_diff': c_v_wr_t1 - c_v_wr_t2,
            
            'batting_ratio': c_t1_bat / (c_t2_bat + 1e-6),
            'bowling_ratio': c_t2_bowl / (c_t1_bowl + 1e-6),
            'form_ratio': c_t1_recent / (c_t2_recent + 1e-6),
            'winrate_ratio': c_t1_overall / (c_t2_overall + 1e-6),
            
            'team_strength_diff': (
                c_t1_overall + c_t1_recent + (c_t1_bat / 100)
                - (c_t2_overall + c_t2_recent + (c_t2_bat / 100))
            )
        }

    def get_score_features(self, bat_team, bowl_team, venue):
        """Extracts precise matchup averages for Score Prediction."""
        if self.df_score is None or self.df_score.empty:
            return self._get_fallback_score_features(bat_team, bowl_team, venue)
            
        df = self.df_score
        team = bat_team
        opponent = bowl_team

        team_data = df[df["batting_team"] == team]
        venue_data = df[df["venue"] == venue]
        opponent_data = df[df["bowling_team"] == opponent]

        def safe_mean(series, default=0.0):
            val = series.mean()
            return default if pd.isna(val) else val

        # Venue averages
        venue_avg_runs = safe_mean(venue_data["total_runs"], 160.0)
        venue_avg_pp_runs = safe_mean(venue_data["pp_runs"], 45.0)
        venue_avg_mid_runs = safe_mean(venue_data["mid_runs"], 70.0)
        venue_avg_death_runs = safe_mean(venue_data["death_runs"], 45.0)

        venue_avg_pp_wickets = safe_mean(venue_data["pp_wickets"], 1.5)
        venue_avg_mid_wickets = safe_mean(venue_data["mid_wickets"], 3.0)
        venue_avg_death_wickets = safe_mean(venue_data["death_wickets"], 2.5)

        # Team averages
        team_avg_runs = safe_mean(team_data["total_runs"], 160.0)
        team_avg_pp_runs = safe_mean(team_data["pp_runs"], 45.0)
        team_avg_mid_runs = safe_mean(team_data["mid_runs"], 70.0)
        team_avg_death_runs = safe_mean(team_data["death_runs"], 45.0)

        # Opponent averages
        opponent_avg_runs_conceded = safe_mean(opponent_data["total_runs"], 160.0)
        opponent_avg_pp_runs_conceded = safe_mean(opponent_data["pp_runs"], 45.0)
        opponent_avg_mid_runs_conceded = safe_mean(opponent_data["mid_runs"], 70.0)
        opponent_avg_death_runs_conceded = safe_mean(opponent_data["death_runs"], 45.0)

        # Recent form
        team_last5_avg_runs = safe_mean(team_data.tail(5)["total_runs"], team_avg_runs)
        opponent_last5_avg_conceded = safe_mean(opponent_data.tail(5)["total_runs"], opponent_avg_runs_conceded)

        # Head to head
        h2h = df[(df["batting_team"] == team) & (df["bowling_team"] == opponent)]
        team_win_rate_vs_opponent = len(h2h) / max(len(team_data), 1)

        # Engineered features
        attack_vs_defense = team_avg_runs - opponent_avg_runs_conceded
        venue_vs_team = venue_avg_runs - team_avg_runs
        recent_vs_average = team_last5_avg_runs - team_avg_runs

        return {
            "batting_team": team,
            "bowling_team": opponent,
            "venue": venue,
            "innings": 1,
            "toss_winner": team,
            "toss_decision": "bat",
            "venue_avg_runs": venue_avg_runs,
            "venue_avg_pp_runs": venue_avg_pp_runs,
            "venue_avg_mid_runs": venue_avg_mid_runs,
            "venue_avg_death_runs": venue_avg_death_runs,
            "venue_avg_pp_wickets": venue_avg_pp_wickets,
            "venue_avg_mid_wickets": venue_avg_mid_wickets,
            "venue_avg_death_wickets": venue_avg_death_wickets,
            "team_avg_runs": team_avg_runs,
            "team_avg_pp_runs": team_avg_pp_runs,
            "team_avg_mid_runs": team_avg_mid_runs,
            "team_avg_death_runs": team_avg_death_runs,
            "opponent_avg_runs_conceded": opponent_avg_runs_conceded,
            "opponent_avg_pp_runs_conceded": opponent_avg_pp_runs_conceded,
            "opponent_avg_mid_runs_conceded": opponent_avg_mid_runs_conceded,
            "opponent_avg_death_runs_conceded": opponent_avg_death_runs_conceded,
            "team_last5_avg_runs": team_last5_avg_runs,
            "opponent_last5_avg_conceded": opponent_last5_avg_conceded,
            "team_win_rate_vs_opponent": team_win_rate_vs_opponent,
            "attack_vs_defense": attack_vs_defense,
            "venue_vs_team": venue_vs_team,
            "recent_vs_average": recent_vs_average
        }
            
    def _get_fallback_match_features(self, team1, team2, venue):
        return {
            'first_innings_team': team1, 'is_team1_batting_first': 1, 'home_advantage': 0.0,
            'h2h_win_rate': 0.5, 'recent_form_t1': 0.5, 'recent_form_t2': 0.5,
            'team1_overall_win_rate': 0.5, 'team2_overall_win_rate': 0.5,
            'avg_score_venue': 160.0, 'toss_venue_win_rate': 0.5,
            'venue_win_rate_t1': 0.5, 'venue_win_rate_t2': 0.5,
            't1_top_batsmen_avg': 35.0, 't2_top_batsmen_avg': 30.0,
            't1_top_bowler_econ': 7.5, 't2_top_bowler_econ': 8.0
        }

    def _get_fallback_score_features(self, bat_team, bowl_team, venue):
        return {
            'innings': 1, 'toss_winner': bat_team, 'toss_decision': 'bat',
            'venue_avg_runs': 160.0, 'venue_avg_pp_runs': 45.0, 'venue_avg_mid_runs': 70.0, 'venue_avg_death_runs': 45.0,
            'venue_avg_pp_wickets': 1.5, 'venue_avg_mid_wickets': 3.0, 'venue_avg_death_wickets': 2.5,
            'team_avg_runs': 160.0, 'team_avg_pp_runs': 45.0, 'team_avg_mid_runs': 70.0, 'team_avg_death_runs': 45.0,
            'opponent_avg_runs_conceded': 160.0, 'opponent_avg_pp_runs_conceded': 45.0, 'opponent_avg_mid_runs_conceded': 70.0, 'opponent_avg_death_runs_conceded': 45.0,
            'team_last5_avg_runs': 160.0, 'opponent_last5_avg_conceded': 160.0, 'team_win_rate_vs_opponent': 0.5,
            'attack_vs_defense': 1.0, 'venue_vs_team': 1.0, 'recent_vs_average': 1.0
        }

    def get_playing11_features(self, team, opponent, venue):
        """Extracts candidate players and their encoded features for a specific match setup"""
        if self.df_playing11 is None or self.df_playing11.empty:
            return pd.DataFrame(), {}, {}
            
        team_code = self.team_reverse.get(team)
        opponent_code = self.opponent_reverse.get(opponent)
        venue_code = self.venue_reverse.get(venue)
        
        if team_code is None or opponent_code is None or venue_code is None:
            return pd.DataFrame(), {}, {} # Invalid input, handled gracefully
            
        # Filter all players historically part of this team
        team_players = self.df_playing11[self.df_playing11['team'] == team_code].copy()
        
        # Override situation to match request
        team_players['opponent'] = opponent_code
        team_players['venue'] = venue_code
        
        return team_players, self.team_map, self.role_map

# Singleton instance
extractor = FeatureExtractor()
